c     Copyright(C) 2001
c     Macromolecular Structure Group of the Biochemsitry Department
c     at the University of California, San Francisco

c     Declares error constants.

      integer IVE_ERR_NONE
      parameter (IVE_ERR_NONE = 0)

      integer IVE_ERR_NO_MEM
      parameter (IVE_ERR_NO_MEM = 1)

      integer IVE_ERR_NO_SPC
      parameter (IVE_ERR_NO_SPC = 2)

      integer IVE_ERR_NO_RESOURCES
      parameter (IVE_ERR_NO_SOURCES = 3)

      integer IVE_ERR_IN_USE
      parameter (IVE_ERR_IN_USE = 10)

      integer IVE_ERR_TIMEOUT
      parameter (IVE_ERR_TIMEOUT = 11)

      integer IVE_ERR_IO
      parameter (IVE_ERR_IO = 20)

      integer IVE_ERR_NO_PERMISSION
      parameter (IVE_ERR_NO_PERMISSION = 30)

      integer IVE_ERR_EXIST
      parameter (IVE_ERR_EXIST = 31)

      integer IVE_ERR_OVERFLOW
      parameter (IVE_ERR_OVERFLOW = 40)

      integer IVE_ERR_UNSUPPORTED
      parameter (IVE_ERR_UNSUPPORTED = 40)

      integer IVE_ERR_INVALID
      parameter (IVE_ERR_INVALID = 512)

      integer IVE_ERR_BAD_FILENAME
      parameter (IVE_ERR_BAD_FILENAME = 513)

      integer IVE_ERR_INTERNAL
      parameter (IVE_ERR_INTERNAL = 1025)

      integer IVE_ERR_UNRECOGNIZED
      parameter (IVE_ERR_UNRECOGNIZED = 1280)
